version: '3.3'
services:
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default